# Generated by Django 5.2.1 on 2025-06-09 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_trabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('ANUNCIO 2D', 'ANUNCIO 2D'), ('ANUNCIO LUMINOSO', 'ANUNCIO LUMINOSO'), ('ARTICULOS PUBLICITARIOS', 'ARTICULOS PUBLICITARIOS'), ('BANDERA PUBLICITARIA', 'BANDERA PUBLICITARIA'), ('DISEÑO', 'DISEÑO'), ('ELECTROSTATICO', 'ELECTROSTATICO'), ('ESTRUCTURA CON LONA', 'ESTRUCTURA CON LONA'), ('ETIQUETAS', 'ETIQUETAS'), ('LETRAS 3D', 'LETRAS 3D'), ('LONA', 'LONA'), ('MICROPERFORADO', 'MICROPERFORADO'), ('NOTA', 'NOTA'), ('PROMOCIONALES', 'PROMOCIONALES'), ('SELLO', 'SELLO'), ('SEÑALETICA', 'SEÑALETICA'), ('SERIGRAFIA', 'SERIGRAFIA'), ('TABLOIDES', 'TABLOIDES'), ('TARJETA', 'TARJETA'), ('TAZAS', 'TAZAS'), ('TEXTIL', 'TEXTIL'), ('TOLDO ENROLLABLE', 'TOLDO ENROLLABLE'), ('TOLDO FIJO', 'TOLDO FIJO'), ('VINIL CON SUAJE', 'VINIL CON SUAJE'), ('VINIL CORTE', 'VINIL CORTE'), ('VINIL IMPRESO', 'VINIL IMPRESO'), ('PLAYERAS', 'PLAYERAS'), ('VOLANTE', 'VOLANTE')], max_length=50)),
                ('entrega', models.CharField(choices=[('Domicilio', 'Domicilio'), ('Galindas', 'Galindas'), ('Instalacion', 'Instalacion')], max_length=50)),
                ('pago', models.CharField(choices=[('Trasferencia', 'Trasferencia'), ('Tarjeta De Credito', 'Tarjeta De Credito'), ('Tarjeta De Debito', 'Tarjeta De Debito'), ('Efectivo', 'Efectivo')], max_length=50)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('incluye_iva', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('factura', models.CharField(blank=True, max_length=100, null=True)),
                ('no_factura', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='notas.nota')),
            ],
        ),
    ]
