# Generated by Django 5.2.1 on 2025-06-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_alter_productonota_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productonota',
            name='nombre',
            field=models.TextField(),
        ),
    ]
