# Generated by Django 5.2.1 on 2025-05-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=13)),
                ('domicilio', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=100)),
                ('detalles', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
    ]
